#!/bin/sh 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
#export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

export ECMWF_FILE_EXT=${ECMWF_FILE_EXT:-1}
#export ECMWF_FILE_EXT=80
####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-ens_tracker}
export RUN=${RUN:-ecme}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEens_tracker=${HOMEens_tracker:-${PACKAGEHOME}}
export EXECens_tracker=${EXECens_tracker:-$HOMEens_tracker/exec}
export FIXens_tracker=${FIXens_tracker:-$HOMEens_tracker/fix}
export USHens_tracker=${USHens_tracker:-$HOMEens_tracker/ush}

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. ./PDY
export PDY=20260316
##############################################
# Define COM directories
##############################################
export DCOM=${DCOM:-/lfs/h2/emc/ens/noscrub/hananeh.jafary/ecmwf_50r1_03242026/20260316/ecmwf}
export COMINgfs=/lfs/h1/ops/prod/com/gfs/v16.3/gfs.${PDY}
export COMINsyn=/lfs/h1/ops/prod/com/gfs/v16.3/syndat

#export COMOUT=${COMOUT:-${COMROOT:?}/ecmwf.${PDY}/${cyc}/products/atmos/cyclone/tracks}
#export COMOUThur=${COMOUThur:-$(compath.py -o ${NET}/${ens_tracker_ver})/global}
#export COMOUTatcf=${COMOUTatcf:-$(compath.py -o ${NET}/${ens_tracker_ver})/atcf}

export COMOUT=/lfs/h2/emc/ptmp/hananeh.jafary/tctrack
export COMOUThur=/lfs/h2/emc/ptmp/hananeh.jafary/global
export COMOUTatcf=/lfs/h2/emc/ptmp/hananeh.jafary/atcf

mkdir -m 775 -p $COMOUT $COMOUThur $COMOUTatcf

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

env

#############################################################
# Execute the script
export cmodel=ecmwf
export ymdh=${PDY}${cyc}

export ecmwfdir=${DCOM}

export pert="p01"
pertdir=${DATA}/${cmodel}/${pert}
mkdir -p $pertdir

#-----------input data checking -----------------
#${USHens_tracker}/data_check.sh
# exit code 6 = missing data of opportunity
#if [ $? -eq 6 ]; then exit; fi
#------------------------------------------------

${USHens_tracker}/extrkr_g1.sh ${ymdh} ${cmodel} ${pert} ${pertdir} #2>&1 >${outfile}
export err=$?; err_chk

#if [ ${SENDCOM} = 'NO' ]; then
#  cp ${pertdir}/trak.emx.atcfunix.${PDY}${cyc} ${COMOUT}/emx.t${cyc}z.cyclone.trackatcfunix
#fi

#############################################################

msg="JOB COMPLETED NORMALLY"
#postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
